// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Yjvq2ekQ4xbFJr7kdmwwDb8ddH23gqs',
    appId: '1:848002826864:web:3af5d617f217160e396ab5',
    messagingSenderId: '848002826864',
    projectId: 'media2-68f72',
    authDomain: 'media2-68f72.firebaseapp.com',
    storageBucket: 'media2-68f72.firebasestorage.app',
    measurementId: 'G-PLCM9Q5WM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHOyrWN0oahrsKSrs53UpG2LQJCMYwBLw',
    appId: '1:848002826864:android:4224eba066e79d47396ab5',
    messagingSenderId: '848002826864',
    projectId: 'media2-68f72',
    storageBucket: 'media2-68f72.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlBna_0JmkyEhkjcgNf-BvUck3Ofb-P1g',
    appId: '1:848002826864:web:41f24c23aa528742396ab5',
    messagingSenderId: '848002826864',
    projectId: 'media2-68f72',
    authDomain: 'media2-68f72.firebaseapp.com',
    storageBucket: 'media2-68f72.firebasestorage.app',
    measurementId: 'G-3HFE4PFBP6',
  );
}
